master:
  "crontab: 0 6 * * *":
    - docker:
        image: node:22
      # 引入您自己的秘钥仓库，以读取 $WEBHOOK_KEY 配置参数值
      imports:
        - https://cnb.cool/Airmole/Airmole-Secret-Repos/-/blob/main/work-wechat.yml
      env:
        WEBHOOK_KEY: $WEBHOOK_KEY
      stages:
        - npm install
        - node ./index.js

  push:
    - docker:
        image: node:22
      # 引入您自己的秘钥仓库，以读取 $WEBHOOK_KEY 配置参数值
      imports:
        - https://cnb.cool/Airmole/Airmole-Secret-Repos/-/blob/main/work-wechat.yml
      env:
        WEBHOOK_KEY: $WEBHOOK_KEY
      stages:
        - npm install
        - node ./index.js